series: yaml-income-test
artifact_storage_uri: /Users/ssc/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/credit.py
  working_directory: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
  data-refinements:
    - refinement:
        name: input_usage


