series: yaml-test
artifact_storage_uri: /home/ssc/Entwicklung/projects/arguseyes/mlruns/

pipeline:
  path: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/paper-example.py
  working_directory: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
    - constant_features
    - label_shift
#    - covariate_shift
    - unnormalised_features
    - traintest_overlap