series: yaml-paper-example-test
artifact_storage_uri: /home/ssc/Entwicklung/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/paper-example.py
  args:
    - Digital_Video_Games
    - !!str 2015-08-01
  working_directory: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
    - label_shift
