series: yaml-income-test
artifact_storage_uri: /home/ssc/Entwicklung/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/income-classifier.py
  working_directory: /home/ssc/Entwicklung/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
    - constant_features
    - label_shift
    - covariate_shift
    - unnormalised_features
    - traintest_overlap
  data-refinements:
    - refinement:
        name: input_usage
    - refinement:
        name: fairness_metrics
        params:
          sensitive_attribute: sex
          non_protected_class: Male
    - refinement:
        name: fairness_metrics
        params:
          sensitive_attribute: race
          non_protected_class: White
    - refinement:
        name: data_valuation

