series: helpful-reviews-label-shift
artifact_storage_uri: /Users/ssc/projects/arguseyes/mlruns/

pipeline:
  template: classification
  path: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/helpful-reviews__label-shift.py
  working_directory: /Users/ssc/projects/arguseyes/arguseyes/example_pipelines/
  detect_issues:
    - label_shift
